[phases.setup]
nixPkgs = ["python3", "ffmpeg", "nodejs", "yt-dlp"]

[phases.install]
cmds = [
    "npm install --prefix backend"
]

[phases.build]
cmds = []

[start]
cmd = "node backend/server.js"

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "20"
